version: "3"

services:
  doc-converter:
    build:
      context: ./doc-converter
      dockerfile: Dockerfile.dev
    volumes:
      - ./doc-converter:/app
    ports:
      - "8000:8000"
    env_file:
      - ./doc-converter/.env
    restart: unless-stopped
    networks:
      - backend
  demo-app:
    build:
      context: ./demo-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./demo-app:/app
    ports:
      - "3000:3000"
    env_file:
      - ./demo-app/.env
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:
    driver: bridge
