name: Build and Publish Docker image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: set lower case repository owner
        run: echo "REPOSITORY_OWNER_LOWERCASE=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push jsontex image
        uses: docker/build-push-action@v5
        with:
          context: ./doc-converter
          push: true
          tags: ghcr.io/${{ env.REPOSITORY_OWNER_LOWERCASE }}/jsontex:latest

      - name: Build and push demo-app image
        uses: docker/build-push-action@v5
        with:
          context: ./demo-app
          push: true
          tags: ghcr.io/${{ env.REPOSITORY_OWNER_LOWERCASE }}/jsontex-demo-app:latest
